dist: trusty

language: python
python:
  - 3.6

git:
  depth: false

install:
  - pip install -r requirements.txt
  - pip install pylint
  - pip install flake8
  - pip install coverage
  - pip install codecov

script:
  - make check PYLINT_BIN=pylint FLAKE8_BIN=flake8 COVERAGE_BIN=coverage

after_success:
 - codecov -t "53d413ee-6b16-47c5-9522-c50e03c65628" -F unittest

notifications:
  email:
    - jakub@thefilaks.net
